name: Build GStreamer Packages

on: 
  push:
  schedule:
  - cron: '27 4 */5 * *'

jobs:
  windows-build:
    env:
      CARGO_HOME: C:\Users\runneradmin\cargo_cache
    runs-on: windows-2022
    strategy:
      matrix:
        version: ["1.26.11", "1.28.5"]
        shared: ["True", "False"]
    steps:
      - uses: actions/checkout@v4
      - run: pip install conan==2.31.1
      - run: conan config install --type dir conan-config-windows
      
      - run: conan create recipes/gst-orc/all --version 0.4.42 -o *:shared=True
      - run: conan create recipes/gst-orc/all --version 0.4.42 -o *:shared=False
      - run: conan create recipes/json-glib/all --version 1.10.6 -o *:shared=${{ matrix.shared }}
      - run: conan install --requires theora/1.1.1 -o *:shared=${{ matrix.shared }} --build theora/1.1.1
      - run: conan install --requires libnice/0.1.23 -o *:shared=${{ matrix.shared }} --build libnice/0.1.23
      - run: conan create recipes/gstreamer/all --version ${{ matrix.version }} -o *:shared=${{ matrix.shared }}
      - run: conan graph info --require gstreamer/${{ matrix.version }} -o *:shared=${{ matrix.shared }} --format html > gstreamer.html

      - uses: actions/upload-artifact@v4
        with:
          name: conan-graph-windows-${{ matrix.version }}-${{ matrix.shared }}
          path: '*.html'

  linux-build:
    env:
      CARGO_HOME: /home/runner/cargo_cache
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: ["1.26.11", "1.28.5"]
        shared: ["True", "False"]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: >
          sudo apt-get install -y libegl-dev libegl1-mesa-dev libvdpau-dev libx11-dev
          libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev
          libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev
          libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev
          libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev
          libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render0-dev
          libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev
          libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev
          libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-cursor-dev
          libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev
          libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev libxcb-util0-dev libva-dev
      - run: pip install conan==2.31.1
      - run: conan config install --type dir conan-config-linux

      - run: conan create recipes/gst-orc/all --version 0.4.42 -o *:shared=True
      - run: conan create recipes/gst-orc/all --version 0.4.42 -o *:shared=False
      - run: conan create recipes/json-glib/all --version 1.10.6 -o *:shared=${{ matrix.shared }}
      - run: conan install --requires theora/1.1.1 -o *:shared=${{ matrix.shared }} --build theora/1.1.1
      - run: conan install --requires libnice/0.1.23 -o *:shared=${{ matrix.shared }} --build libnice/0.1.23
      - run: conan create recipes/gstreamer/all --version ${{ matrix.version }} -o *:shared=${{ matrix.shared }}
      - run: conan graph info --require gstreamer/${{ matrix.version }} -o *:shared=${{ matrix.shared }} --format html > gstreamer.html

      - uses: actions/upload-artifact@v4
        with:
          name: conan-graph-linux-${{ matrix.version }}-${{ matrix.shared }}
          path: '*.html'
